#include <iostream>
using namespace std;
int main() {
	setlocale(0, "");
	int a1 = 11;
	int a2 = 12;
	int a3 = 13;
	int a4 = 14;
	int a5 = 15;
	int a6 = 16;
	int a7 = 17;
	int a8 = 18;
	int a9 = 19;
	int a10 = 20;
	cout << "a_1: " << a1 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_2: " << a2 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_3: " << a3 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_4: " << a4 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_5: " << a5 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_6: " << a6 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_7: " << a7 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_8: " << a8 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_9: " << a9 << " | Тип данных : int, размер:4б." << endl;
	cout << "a_10: " << a10 << " | Тип данных : int, размер:4б." << endl << endl;
	char b1 = 1;
	char b2 = 2;
	char b3 = 3;
	char b4 = 4;
	char b5 = 5;
	char b6 = 6;
	char b7 = 14;
	char b8 = 13;
	char b9 = 12;
	char b10 = 11;
	cout << "b_1: " << b1 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_2: " << b2 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_3: " << b3 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_4: " << b4 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_5: " << b5 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_6: " << b6 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_7: " << b7 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_8: " << b8 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_9: " << b9 << " | Тип данных : char, размер:2б." << endl;
	cout << "b_10: " << b10 << " | Тип данных : char, размер:2б." << endl << endl;
	short c1 = -11;
	short c2 = 12;
	short c3 = -13;
	short c4 = 14;
	short c5 = -15;
	short c6 = 16;
	short c7 = -17;
	short c8 = 18;
	short c9 = -19;
	short c10 = 20;
	cout << "c_1: " << c1 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_2: " << c2 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_3: " << c3 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_4: " << c4 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_5: " << c5 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_6: " << c6 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_7: " << c7 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_8: " << c8 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_9: " << c9 << " | Тип данных : short, размер:2б." << endl;
	cout << "c_10: " << c10 << " | Тип данных : short, размер:2б." << endl << endl;
	long d1 = 11;
	long d2 = 12;
	long d3 = 13;
	long d4 = 14;
	long d5 = 15;
	long d6 = 16;
	long d7 = 17;
	long d8 = 18;
	long d9 = 19;
	long d10 = 20;
	cout << "d_1: " << d1 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_2: " << d2 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_3: " << d3 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_4: " << d4 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_5: " << d5 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_6: " << d6 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_7: " << d7 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_8: " << d8 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_9: " << d9 << " | Тип данных : long, размер:8б." << endl;
	cout << "d_10: " << d10 << " | Тип данных : long, размер:8б." << endl << endl;
	float f1 = 11.11;
	float f2 = 12.12;
	float f3 = 13.13;
	float f4 = 14.14;
	float f5 = 15.15;
	float f6 = 16.16;
	float f7 = 17.17;
	float f8 = 18.18;
	float f9 = 19.19;
	float f10 = 20.20;
	cout << "f_1: " << f1 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_2: " << f2 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_3: " << f3 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_4: " << f4 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_5: " << f5 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_6: " << f6 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_7: " << f7 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_8: " << f8 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_9: " << f9 << " | Тип данных : float, размер:4б." << endl;
	cout << "f_10: " << f10 << " | Тип данных : float, размер:4б." << endl << endl;
	double r1 = 11;
	double r2 = 12;
	double r3 = 13;
	double r4 = 14;
	double r5 = 15;
	double r6 = 16;
	double r7 = 17;
	double r8 = 18;
	double r9 = 19;
	double r10 = 20;
	cout << "r_1: " << r1 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_2: " << r2 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_3: " << r3 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_4: " << r4 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_5: " << r5 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_6: " << r6 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_7: " << r7 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_8: " << r8 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_9: " << r9 << " | Тип данных : double, размер:8б." << endl;
	cout << "r_10: " << r10 << " | Тип данных : double, размер:8б." << endl << endl;
	bool af1 = true;
	bool af2 = false;
	bool af3 = true;
	bool af4 = false;
	bool af5 = true;
	bool af6 = true;
	bool af7 = false;
	bool af8 = true;
	bool af9 = false;
	bool af10 = true;
	cout << "af_1: " << af1 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_2: " << af2 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_3: " << af3 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_4: " << af4 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_5: " << af5 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_6: " << af6 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_7: " << af7 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_8: " << af8 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_9: " << af9 << " | Тип данных : bool, размер:1б." << endl;
	cout << "af_10: " << af10 << " | Тип данных : bool, размер:1б." << endl << endl;


	return 0;
	
}
